- amulet_map_editor/plugins/programs/edit/controllable_canvas.py
This moves tracking mouse position deltas to mouse movement event handler which seems to work far more reliably than using a timer
> Fix unreliable camera rotation

- amulet_map_editor/opengl/canvas/base.py
- amulet_map_editor/programs/edit/canvas/ui/tool/tools/select.py
- amulet_map_editor/programs/edit/plugins/stock_plugins/import_operations/construction.py
- amulet_map_editor/programs/edit/plugins/stock_plugins/import_operations/mcstructure.py
- amulet_map_editor/programs/edit/plugins/stock_plugins/import_operations/schematic.py
This pull request is part of the one in Amulet-Core
https://github.com/Amulet-Team/Amulet-Core/pull/77
> Added a block_palette attribute to the chunk class

- amulet_map_editor/programs/edit/canvas/controllable_edit_canvas.py
Moved the inspect block logic to its own method and cleaned up the logic a bit
> Inspect block cleanup

- amulet_map_editor/api/framework/pages/world_page.py
- amulet_map_editor/api/opengl/mesh/level/level.py
- amulet_map_editor/api/wx/ui/select_world.py
- amulet_map_editor/programs/convert/convert.py
- amulet_map_editor/programs/edit/plugins/stock_plugins/export_operations/construction.py
- amulet_map_editor/programs/edit/plugins/stock_plugins/export_operations/mcstructure.py
- amulet_map_editor/programs/edit/plugins/stock_plugins/export_operations/schematic.py
- amulet_map_editor/programs/edit/plugins/stock_plugins/import_operations/construction.py
- amulet_map_editor/programs/edit/plugins/stock_plugins/import_operations/mcstructure.py
- amulet_map_editor/programs/edit/plugins/stock_plugins/import_operations/schematic.py
The changes to support the rewrite of the interface in amulet-core
https://github.com/Amulet-Team/Amulet-Core/pull/95
> Rewrite interface

- amulet_map_editor/api/opengl/mesh/level/level.py
- amulet_map_editor/programs/convert/convert.py
- amulet_map_editor/programs/edit/edit.py
Some references were still referring to the old location causing things to break
> Fix references

- amulet_map_editor/lang/fr_FR.lang
I just fixed some details in the french translation.
I saw in the contributing.md that I'm supposed to run some tests. I don't know if it implies any test unit or whatever, but I launched the app with the updated translation file and everything seemed fined.
It is the first time I do a pull request by the way, so if I did anything wrong feel free to tell me.
> Fixed FR translations

- amulet_map_editor/programs/edit/api/behaviour/raycast_behaviour.py
> Fixed selection to treat cave air like air

- amulet_map_editor/programs/edit/api/behaviour/block_selection_behaviour.py
- amulet_map_editor/programs/edit/api/behaviour/raycast_behaviour.py
- amulet_map_editor/programs/edit/plugins/tools/select.py
This fixes some issues with selecting and modifying the selection boxes.
There were some issues before where blocks within the selection would be selected before the selection.
It was also just a bit unpredictable at times.
This should fix those issues.
It also optimises the code that gets the list of blocks along a look vector.
Also fixes a bug where the select UI did not update when undoing and redoing
> Fix selection

- .gitignore
- amulet_map_editor/api/opengl/resource_pack/resource_pack.py
- amulet_map_editor/api/opengl/textureatlas.py
This should make it slightly quicker to load the 3D editor after the first load by caching the merged atlas texture
> Optimise 3d editor load

- amulet_map_editor/programs/edit/api/ui/tool/base_tool_ui.py
- amulet_map_editor/programs/edit/plugins/operations/stock_plugins/export_operations/construction.py
- amulet_map_editor/programs/edit/plugins/operations/stock_plugins/export_operations/mcstructure.py
- amulet_map_editor/programs/edit/plugins/operations/stock_plugins/export_operations/schematic.py
- amulet_map_editor/programs/edit/plugins/operations/stock_plugins/export_operations/sponge_schematic.py
- amulet_map_editor/programs/edit/plugins/tools/import_tool.py
- requirements.txt
Requires Amulet-Team/Amulet-Core/pull/118
Adds a reader and writer for the sponge schematic format.
Adds an export UI for the sponge schematic.
Small fixes and changes
> Impl sponge schematic

- amulet_map_editor/api/framework/amulet_ui.py
This was causing issues and I don't think we actually use it
> Removed wx lang value

- amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py
- requirements.txt
Many users have got stuck when the resource pack fails to load.
This should add some better (lower level) output messages and also tell the user to restart the program
> Added message box if the resource pack fails to load

- amulet_map_editor/api/wx/util/button_input.py
- amulet_map_editor/lang/en.lang
- amulet_map_editor/programs/edit/api/canvas/edit_canvas.py
- amulet_map_editor/programs/edit/api/ui/nudge_button.py
- amulet_map_editor/programs/edit/api/ui/tool_manager.py
- amulet_map_editor/programs/edit/edit.py
- amulet_map_editor/programs/edit/plugins/tools/select.py
Added nudge buttons for both points of the active box both together and individually.
Added a label stating how big the selection box is.
Moved all the strings into the lang files so they can be localised.
Added tooltips to each of the elements to help users.
Propagated enable and disable events down to the tools.
Exposed the key config through a property in the canvas.
Modified the button input api slightly
> Improve select tool

- .github/workflows/nightly.yml
- .github/workflows/python-build.yml
This adds nightly builds if the repository has changed.
This still needs some work but I need to merge into master to test it.
> Impl nightly

- amulet_map_editor/api/opengl/camera/camera.py
- amulet_map_editor/api/opengl/canvas/event_canvas.py
- amulet_map_editor/api/opengl/mesh/selection/box/render_selection.py
- amulet_map_editor/api/opengl/mesh/selection/box/render_selection_editable.py
- amulet_map_editor/lang/en.lang
- amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py
- amulet_map_editor/programs/edit/plugins/tools/chunk.py
- amulet_map_editor/programs/edit/plugins/tools/select.py
Added a minimum and maximum draw coordinate when in 2D mode.
Moved all strings into the lang files.
> Improve chunk tool

- amulet_map_editor/api/opengl/mesh/level/chunk/chunk.py
- amulet_map_editor/api/opengl/mesh/level/chunk/chunk_builder.py
This is a tiny bit faster but not by much.
> Optimised geometry creation a little

- amulet_map_editor/lang/fr.lang
Add new translations for select tool & goto ui + fix some older entries
> Update FR translations

- amulet_map_editor/__main__.py
- amulet_map_editor/api/framework/__init__.py
- amulet_map_editor/api/framework/amulet_ui.py
- amulet_map_editor/api/framework/app.py
Created a subclass of the app class.
Modified locale setup method to fix locale issues on some systems.
> Fix locale

- amulet_map_editor/api/opengl/mesh/level/chunk/chunk.py
- amulet_map_editor/api/opengl/mesh/level/level.py
- amulet_map_editor/api/opengl/mesh/level/region.py
- amulet_map_editor/api/opengl/mesh/level_group.py
- amulet_map_editor/api/opengl/mesh/selection/box/render_selection.py
- amulet_map_editor/api/opengl/mesh/selection/box/render_selection_editable.py
- amulet_map_editor/programs/edit/api/renderer.py
There was previously a large stuttering due to merging of chunk geometry into one large array.
This was done on the main thread which locked up rendering while it was processing.
This moves it into the thread with chunk generation.
> Fix stutter

- amulet_map_editor/api/opengl/camera/camera.py
- amulet_map_editor/api/opengl/camera/controllable_camera.py
- amulet_map_editor/api/opengl/mesh/selection/box/render_selection.py
- amulet_map_editor/api/opengl/mesh/selection/box/render_selection_editable.py
- amulet_map_editor/api/opengl/mesh/selection/group/render_selection_group.py
- amulet_map_editor/api/wx/util/button_input.py
- amulet_map_editor/api/wx/util/mouse_movement.py
- amulet_map_editor/programs/edit/api/selection.py
Replaces all `type(obj) is <class>` type checks with `isinstance(obj, <class>)` calls
> Use isinstance() for type checking instead of type()

- amulet_map_editor/api/framework/pages/world_page.py
- amulet_map_editor/api/opengl/mesh/level_group.py
- amulet_map_editor/api/wx/ui/select_world.py
- amulet_map_editor/programs/edit/api/behaviour/chunk_selection_behaviour.py
- amulet_map_editor/programs/edit/api/behaviour/inspect_block_behaviour.py
- amulet_map_editor/programs/edit/edit.py
- amulet_map_editor/programs/edit/plugins/operations/stock_plugins/operations/set_biome.py
- requirements.txt
https://github.com/Amulet-Team/Amulet-Core/pull/130 changed a few minor things about the API.
This updates the editor to use the new version
> Update api calls

- amulet_map_editor/api/framework/pages/world_page.py
Previously the position of programs was a little random between running from source and the compiled builds.
This should fix that.
> Sorted sub-programs alphabetically

- amulet_map_editor/api/opengl/mesh/level_group.py
- amulet_map_editor/api/opengl/mesh/selection/box/render_selection.py
- amulet_map_editor/api/opengl/mesh/selection/box/render_selection_editable.py
- amulet_map_editor/programs/edit/plugins/tools/chunk.py
These attributes are apparently depreciated.
Removed them and replaced them with direct manipulation of the state.
This should hopefully fix #244
> removed glPushAttrib and glPopAttrib calls

- amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py
- amulet_map_editor/programs/edit/api/ui/file.py
- requirements.txt
Once the canvas is loaded, teleport to the location and dimension of the local player.
This requires the changes in https://github.com/Amulet-Team/Amulet-Core/pull/131
> Teleport to the local player location upon load

- amulet_map_editor/api/opengl/mesh/level/chunk/chunk.py
- amulet_map_editor/api/opengl/mesh/level/level.py
- amulet_map_editor/api/opengl/mesh/level_group.py
- amulet_map_editor/programs/edit/api/behaviour/chunk_selection_behaviour.py
- amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py
- amulet_map_editor/programs/edit/api/canvas/edit_canvas.py
- amulet_map_editor/programs/edit/api/renderer.py
- amulet_map_editor/programs/edit/api/ui/file.py
- amulet_map_editor/programs/edit/plugins/tools/chunk.py
Modified the floor tiles to display at the bottom of the usable world and added ceiling tiles.
> Added support for 1.17 worlds

- amulet_map_editor/api/opengl/mesh/level/chunk/chunk.py
- amulet_map_editor/api/opengl/mesh/level/level.py
- amulet_map_editor/api/opengl/mesh/level_group.py
- amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py
Fixed a renderer issue in the paste tool
> Fixed Paste tool render issue

- amulet_map_editor/programs/edit/plugins/operations/stock_plugins/internal_operations/prune_chunks.py
- amulet_map_editor/programs/edit/plugins/tools/chunk.py
Delete chunks previously took a while because it had to load each chunk.
Added a UI to ask the user if they want to load the chunks or not.
> Added a way to side-step the original chunk loading process

- amulet_map_editor/lang/de.lang
Hi,
native german here. Some translations sounded like they were done through google translate so I updated them a little bit.
> improve german translations

- amulet_map_editor/__main__.py
> Fixed an issue with wxpython and linux

- amulet_map_editor/programs/edit/api/ui/tool/base_operation_choice.py
If an operation fails to load for some reason this will destroy the created UI and restore everything back to the starting state.
Once this is done the traceback is show to the user.
The user can modify the code to fix the issue and reload the operations and it should appear.
This should fix #346
> Handled Operation UI errors and remove the UI

- amulet_map_editor/programs/edit/plugins/tools/chunk.py
https://github.com/Amulet-Team/Amulet-Map-Editor/issues/379
Fixes a typo in one of the popups
> Fix for issue #379

- amulet_map_editor/api/framework/update_check.py
I have added a better regex match that matches every version we have released and every format we will release.
I don't think it will break anything you have changed but double check it.
I also converted the release stages to an enum
> Improv fix update checking

- amulet_map_editor/__main__.py
Fixed file writing issue. Not sure how this was missed when first written.
Added traceback to the error log
> Fixed error logging when the program crashes

- amulet_map_editor/programs/edit/api/canvas/edit_canvas.py
This will allow the first thread that calls it to run and hold back the second thread until the first is finished.
This uses the RLock class so that if the same thread calls the method again it will be allowed through but then throw an exception rather than get stuck acquiring the lock.
> Removed stack inspection from run_operation and made thread safe

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
The old templates were missing prompts for useful information.
This cleans up the templates and adds some more details to hopefully reduce the number of questions we need to ask.
> Improved issue templates

- amulet_map_editor/programs/edit/api/operations/manager/operation_manager.py
Fixed an issue where operations would not get reloaded.
Fixed syntax errors in operations crashing the 3D Editor program.
Fixes #549
> Fix operation reload

- .github/workflows/python-build.yml
> Bumped the pyinstaller version

- .github/workflows/python-stylecheck.yml
- .github/workflows/python-unittests.yml
The tests will now run on pull requests to all branches.
The push trigger will run on master, main (if we rename the main branch) and any version number branch if we switch to this name scheme
> Modified tests triggers

- amulet_map_editor/lang/cs.lang
- Fixed incorrect translations in `cs.lang`
- Added all missing translations to `cs.lang`
> Updated Czech translations

- amulet_map_editor/api/framework/amulet_ui.py
- amulet_map_editor/api/wx/ui/simple.py
- amulet_map_editor/programs/convert/convert.py
- amulet_map_editor/programs/edit/plugins/tools/paste.py
- amulet_map_editor/programs/edit/plugins/tools/select.py
Users with smaller screens were having issues with parts of the UI being cropped off.
This adds scroll bars to UI so that those users can scroll to see the rest of the UI.
Fixes #450
> Solved some of the scaling issues

- amulet_map_editor/api/opengl/resource_pack/resource_pack.py
> Fixed ValueError: max() arg is an empty sequence

- amulet_map_editor/api/framework/pages/main_menu.py
- amulet_map_editor/lang/cs.lang
- amulet_map_editor/lang/de.lang
- amulet_map_editor/lang/en.lang
- amulet_map_editor/lang/fr.lang
- amulet_map_editor/lang/id.lang
- amulet_map_editor/lang/ja.lang
- amulet_map_editor/lang/ko.lang
- amulet_map_editor/lang/ru.lang
- amulet_map_editor/lang/vi.lang
- amulet_map_editor/lang/zh_CN.lang
- amulet_map_editor/lang/zh_TW.lang
Renamed the `Help` button to `User Manual` to be more descriptive.
Added a button to the main menu that links to the bug tracker.
> Added a bug tracker button to the main menu

- amulet_map_editor/api/wx/util/validators.py
- amulet_map_editor/programs/edit/plugins/tools/select.py
This was originally a partial fix for #407.
Upon further investigation it was found that it was actually a bug in wxWidgets which has been fixed.
This pull request includes the refactoring from trying to fix that issue.
> Refactored Select Tool

- amulet_map_editor/programs/edit/plugins/operations/examples/licence.md
- amulet_map_editor/programs/edit/plugins/operations/stock_plugins/operations/clone.py
- amulet_map_editor/programs/edit/plugins/operations/stock_plugins/operations/fill.py
- amulet_map_editor/programs/edit/plugins/operations/stock_plugins/operations/replace.py
- amulet_map_editor/programs/edit/plugins/operations/stock_plugins/operations/set_biome.py
- amulet_map_editor/programs/edit/plugins/operations/stock_plugins/operations/waterlog.py
This will make it possible for users to create operations based upon these examples
> Added MIT licences to operations

- amulet_map_editor/api/opengl/mesh/level/chunk/chunk_builder.py
- amulet_map_editor/api/opengl/mesh/level/region.py
- amulet_map_editor/api/opengl/mesh/selection/box/render_selection.py
- amulet_map_editor/api/opengl/mesh/sky_box.py
- amulet_map_editor/api/opengl/mesh/tri_mesh.py
- amulet_map_editor/api/opengl/shaders/__init__.py
The texture was sometimes being generated in a different thread (the one that generated the chunk) leading to an error.
Moved the texture acquisition step into the draw function so it will always be called from the main thread.
Moved the resource pack class into TriMesh
This was an issue created by #678
> Fixed glGenTextures error

- .github/workflows/python-unittests.yml
- MANIFEST.in
- pyproject.toml
- requirements.txt
- setup.cfg
- setup.py
Moved settings into setup.cfg
Moved requirements into setup.cfg and removed requirements.txt
Cleaned up manifest.in
> Improved packaging system
