Amulet-Team/Amulet-Map-Editor

.travis.yml
Amulet.spec

Travis builds are now only triggered when both of the following conditions are met:
- The commit was pushed to the `master` branch
- The contents of the `amulet_map_editor/version` file have changed and that there are no existing tags that have the value `v<version>` where `<version>` is the contents of the file

Fixed Travis CI Build Process

---

amulet_map_editor/programs/edit/canvas/controllable_edit_canvas.py
amulet_map_editor/programs/edit/canvas/edit_canvas.py
amulet_map_editor/programs/edit/canvas/ui/tool/__init__.py
amulet_map_editor/programs/edit/canvas/ui/tool/tool.py
amulet_map_editor/programs/edit/canvas/ui/tool/tools/base_operation.py
amulet_map_editor/programs/edit/canvas/ui/tool/tools/base_tool_ui.py
amulet_map_editor/programs/edit/canvas/ui/tool/tools/export_tool.py
amulet_map_editor/programs/edit/canvas/ui/tool/tools/import_tool.py
amulet_map_editor/programs/edit/canvas/ui/tool/tools/operation.py
amulet_map_editor/programs/edit/canvas/ui/tool/tools/select.py

If any other tool is enabled (eg the operation tool) and the deselect action is run it will switch to the select tool.
Once in the select tool the command will deselect the actual box.
This is essentially just a shortcut to get to the select tool.

Deselect first switches to the select tool when other tools are enabled

---

amulet_map_editor/api/framework/amulet_ui.py
amulet_map_editor/api/wx/ui/select_world.py
amulet_map_editor/api/wx/util/ui_preferences.py

This system allows for any custom window/dialog that we have created to save/restore it's position/size when initialized without requiring a full rewrite of the target class or our base UI classes.
Solution for #99 
- For any custom UI window/dialog, adding the `@preserve_ui_preferences` decorator (from the `amulet_map_editor.api.wx.util.ui_preferences` module) to the class declaration modifies the classes `__init__` method to preserve the previous behaviour while adding the additional attributes needed and 3 new event handlers (all contained within the `ui_preferences` module)
- No other changes are needed to the target UI class to achieve this behaviour
- All data is stored the `config/window_preferences.config` file as a JSON object once Amulet exits
- _Note: Unexpected program …

Preserve positions and sizes of windows between program launches

---

amulet_map_editor/api/wx/util/ui_preferences.py

The wrapper was blocking the resize event which meant that contained objects were only resizing when the mouse was released.

Fixed an issue with the wrapper blocking events

---

amulet_map_editor/api/opengl/mesh/level/level.py
amulet_map_editor/programs/edit/canvas/base_edit_canvas.py

Previously when changing dimension due to the more optimised chunk loading logic sometimes parts of the previous dimension would stay and parts of the new dimension would not get loaded until you moved a bit. This should fix that.

Fixed some issues changing dimension

---

amulet_map_editor/programs/edit/api/behaviour/camera_behaviour.py

Before when returning from 2D mode the camera would be facing straight down.
This stores the original camera rotation and restores it when returning back to 3D mode

Restore original camera rotation when returning from 2D mode

---

amulet_map_editor/api/opengl/camera/camera.py
amulet_map_editor/programs/edit/edit.py

There was a case where the fov could be set to greater than 180 which would flip the renderer upside down.
This should fix that.
This was caused by the fov in perspective and orthographic mode sharing the same attribute. This adds in attributes for each of them.

Fixed the renderer appearing upside down

---

amulet_map_editor/api/wx/util/mouse_movement.py
amulet_map_editor/programs/edit/api/behaviour/camera_behaviour.py
amulet_map_editor/programs/edit/api/behaviour/raycast_behaviour.py

If the screen gets minimised it is possible for the size to be zero making a divide by zero error

Fixed some divide by zero issues

---

amulet_map_editor/api/wx/util/button_input.py
amulet_map_editor/programs/edit/api/renderer.py
amulet_map_editor/programs/edit/api/selection.py

There were some issues where the program would crash due to timer accessing windows that no longer existed. This will disable the timers when the window is destroyed to make sure that does not happen

Disable timers on window destroy

---

amulet_map_editor/api/opengl/camera/camera.py
amulet_map_editor/api/opengl/mesh/level_group.py
amulet_map_editor/api/opengl/mesh/selection/box/render_selection.py
amulet_map_editor/api/opengl/mesh/selection/box/render_selection_editable.py
amulet_map_editor/lang/en.lang
amulet_map_editor/programs/edit/api/behaviour/camera_behaviour.py
amulet_map_editor/programs/edit/plugins/tools/paste.py
requirements.txt

This is a large overhaul of the paste tool.
It adds a nudge button to move around the pasted selection.
It adds the ability to scale the pasted structure in each axis.
It adds the ability to mirror the structure through negative scale values.
It adds rotation in degree increments which can be enabled by the free rotation toggle.
Added buttons to rotate and mirror based on the camera's orientation.
Redesigned the UI to make it easier to understand.
Made the matrices in the camera class immutable.
Requires Amulet-Team/Amulet-Core/pull/127

Upgrade paste tool

---

amulet_map_editor/api/wx/util/button_input.py
amulet_map_editor/programs/edit/api/renderer.py
amulet_map_editor/programs/edit/api/selection.py

This was caused by an operation being destroyed.
The event propagated upwards and was caught by these events when it should not have been.
This makes it so that they will only receive the event if the parent is the one creating the event.

Fixed program freeze

---

amulet_map_editor/api/lang.py

locale.getdefaultlanguage can return None if the language cannot be found.
Fixes #283

Fall back to default language if language is None

---

.github/workflows/python-build.yml

We will remove this at some point in the future when the new version does not trip antivirus programs up

Locked pyinstaller to 4.2

---

amulet_map_editor/api/lang.py
amulet_map_editor/lang/en.lang
amulet_map_editor/lang/fr.lang
tests/test_lang.py

I added comments support for lang files and updated the `test_lang.py`.
Basically it allows comments lines to be written by starting them with the `#` symbol.
It also allows leading spaces before the `#` symbol, which probably won't be useful but made sense since leading spaces were already supported for normal lines.
Anyway, the purpose of this is to help contributors to better define sections in their own language (namespaces identifiers are self-speaking but they are in english). It also allows us to write notes, instructions, and info about some specific features which translators might not know (I'm thinking of the `&` in the menubar translations for example).
_Black has been used, `test_lang.py` has been ran successfully._

Add comments support for lang files

---

amulet_map_editor/api/framework/pages/world_page.py
amulet_map_editor/api/opengl/canvas/canvas.py
amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py
amulet_map_editor/programs/edit/api/canvas/edit_canvas.py
amulet_map_editor/programs/edit/api/ui/file.py

Some worlds take a while to close (particularly Bedrock which runs the compaction logic on close) and the program will hang while this is happening.
Added a dialog to reassure the user that something is happening and the program has not crashed.
This should fix #321 
Fixed a recursion issue when closing from the button in the canvas.
Fixed a crash when closing from the button in the canvas and saving.

Added a loading bar when closing worlds

---

amulet_map_editor/api/framework/pages/world_page.py
amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py

fixes #308 
Previously if there was an error while enabling or disabling a sub-program there would be a silent error.
This shows that error to the user via a dialog so that they are aware of it.
Once they click okay the sub-program will be destroyed.

Catch errors and display them to the user if a sub-program failed to load

---

amulet_map_editor/api/framework/amulet_ui.py
amulet_map_editor/lang/en.lang
amulet_map_editor/lang/fr.lang
amulet_map_editor/lang/zh_CN.lang
amulet_map_editor/lang/zh_TW.lang
amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py

When running from source on macOS you need to run the install certificates file.
This is mentioned in the installer but a number of users has missed this and the error that is given is a little cryptic.
Hopefully this should make it more clear to those users.
Split up the lang entries to make it easier to add more errors

Added a warning dialog about installing certificates on macOS

---

amulet_map_editor/api/framework/amulet_ui.py
amulet_map_editor/api/framework/pages/world_page.py
amulet_map_editor/api/wx/ui/traceback_dialog.py
amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py
amulet_map_editor/programs/edit/api/canvas/edit_canvas.py
amulet_map_editor/programs/edit/api/ui/tool/default_base_tool_ui.py
amulet_map_editor/programs/edit/plugins/tools/import_tool.py

A lot of users have been reporting issues and we have to ask them for the traceback because it is currently hidden in the console.
This UI displays the traceback within the UI that is shown to the user with the ability to copy the traceback to the clipboard.
This should make it easier for users to report issues.

Added an error UI that also displays the traceback

---

amulet_map_editor/api/opengl/__init__.py
amulet_map_editor/programs/edit/__init__.py

macOS changed some things with opengl in one of the newer releases which means that opengl cannot be imported.
This should patch the loading logic to find the new location if opengl failed to load.
This should fix #226

Fix opengl on macOS

---

amulet_map_editor/programs/edit/plugins/operations/stock_plugins/operations/replace.py
amulet_map_editor/programs/edit/plugins/operations/stock_plugins/operations/set_biome.py
amulet_map_editor/programs/edit/plugins/operations/stock_plugins/operations/waterlog.py

The previously used method loaded all of the chunks.
This means the loading bar would stay at 0 for a little bit.
The replaced method should be quicker and the chunk loading done while the loading bar is updated.

Switched out get_chunk_slice_box for get_coord_box

---

amulet_map_editor/__main__.py

When starting on linux, amulet almost immediately crashes, returning this as part of the traceback:
if sys.platform == "linux" and wx.__version__.VERSION >= (4, 1, 1):
AttributeError: 'str' object has no attribute 'VERSION'
It seems that wx moved the tuple version information, which I updated to match. The proposed fix has been tested with Python 3.7 on Debian 10.1, and with Python 3.9 on a recent Debian Testing.

Updated location of wx.VERSION for linux

---

amulet_map_editor/__main__.py

If part of Amulet was missing, the error would happen outside the existing try except block.
This moves the imports into a try except block so that if an error does occur it can be reported correctly.
This fixes #368

Moved imports in __main__ into a try except block

---

amulet_map_editor/api/framework/update_check.py

Implemented a better update checking system, that now correctly identifies our versioning scheme.
Changes:
- Checking whether an update is valid is now based off of a version hierarchy (IE: Full releases only notify will notify users of new full releases, running a beta build will notify users of new beta or full releases, etc.)
- New nightly builds are correctly identified
- More efficient and accurate newest release finding
- The old finding code sometimes would just find the next newest version, not the actual newest version
- Rudimentary checking for when running from source with a git installation to not show the update dialog

Fixed update check to now support beta/alpha/nightly releases

---

amulet_map_editor/api/framework/update_check.py

The old code was recommending an older full release over the newer beta.

Fixed update check

---

amulet_map_editor/api/framework/amulet_ui.py
amulet_map_editor/api/wx/util/ui_preferences.py
amulet_map_editor/programs/edit/api/chunk_generator.py

There were a number of issues with the code that saved and restored the window size after restarting the program.
Added an `is_full_screen` attribute to the config file to track if the window is full screen or not.
Restore the window to either windowed in the same location or full screen depending on the previous state.
Fixed an issue where the window started in full screen but showed the restore down button.
Made the window start in full screen the first time the program is loaded.
The config file now stores the non-maximised size. This allows the window to be start in full screen but be restored down to the size before full screening.
Increased the default app size a bit to fix #467

Fix window size restoring issues

---

amulet_map_editor/api/framework/pages/world_page.py
amulet_map_editor/programs/edit/api/operations/manager/operation_manager.py
amulet_map_editor/programs/edit/api/operations/manager/util.py

PyInstaller has fixed an issue where frozen modules would not appear in pkgutil.iter_modules. This meant that the frozen modules were found and loaded twice now that it has been fixed.
Imports are now done purely through `importlib.import_module`
External modules are first added to the path which should resolve some issues with operations that are packages.
This fixes #511

Improved dynamic import code

---

amulet_map_editor/programs/edit/edit.py

The edit program was checking if the world had changed and stopped closing if there were changes.
Previously this was fine since it was the only sub-program that could edit the world but if more programs are added this would silently stop the program from closing.
Fixes #526

Fixed the close logic stopping the program from closing

---

requirements.txt

We use wx.Image.SetDefaultLoadFlags which only exists in 4.1 and up.
Linux comes with an older version of wxpython which means the new one is not installed causing an error.
This will force the new version.

Increased minimum requirement for wxpython

---

amulet_map_editor/programs/edit/plugins/operations/stock_plugins/internal_operations/delete.py

Fixes #550 
Modified delete operation to only delete blocks in chunks that exists.
This means that chunks that do not exist will not be created.

Delete blocks does not create chunks

---

amulet_map_editor/api/framework/pages/world_page.py

Previously when the world was closed there was always a dialog that popped up to notify the user that it might take a while. This always shown even if only instantaneously.
This moves the closing logic to a new thread so that it does not block the UI and the closing notification is only shown if it takes more than 0.1 seconds to close.
This also fixes an issue where the UI would become unresponsive if the world save code ran too quickly. This was due to the close notification being present but hidden. I think this was related to dialog's parent being destroyed. Removing the parent seems to fix this.

Improved world closing UI

---

amulet_map_editor/programs/edit/edit.py

On some platforms this throws an error if the value is a float
Fixes #584

Int value before giving to SetValue

---

amulet_map_editor/programs/edit/api/ui/nudge_button.py

The nudge buttons used to sound the system invalid sound whenever it was used.
This style lets the window know that it should take key inputs thus disabling the system sound.
Fixes https://github.com/Amulet-Team/Amulet-Map-Editor/issues/272

fix system sound on nudge button

---

amulet_map_editor/api/framework/amulet_ui.py
amulet_map_editor/api/framework/update_check.py
requirements.txt

The previous method relied on custom parsing and comparison.
This switches to the packaging library which handles all of that for us.
Split up the logic a bit to make testing easier.
Replaced CheckForUpdate class with a function passed to the thread.
Versions will only be suggested if they are newer and more stable. This was the intended behaviour before but it was a little broken.

Improved the update check mechanic

---

amulet_map_editor/programs/edit/api/canvas/edit_canvas.py
amulet_map_editor/programs/edit/api/events.py
amulet_map_editor/programs/edit/api/ui/tool/base_tool_ui.py
amulet_map_editor/programs/edit/api/ui/tool_manager.py
amulet_map_editor/programs/edit/plugins/tools/paste.py

Changes the behaviour of the paste tool mechanic to automatically bring up the last copied structure when opened. Before the UI would remain greyed out.
Replaced the paste event with an extra attribute in the tool change event.
Fixed #618

Paste latest when opening paste tool

---

amulet_map_editor/programs/edit/api/operations/manager/operation_manager.py
amulet_map_editor/programs/edit/api/ui/tool/base_operation_choice.py
amulet_map_editor/programs/edit/plugins/tools/export_tool.py

The operation could be difficult to find.
This adds a button to the right of the reload button that when clicked will open the folder where the operations are loaded from in the system explorer.
Fixed #453

Added a button to open the operation folder

---

amulet_map_editor/api/opengl/camera/camera.py

When the camera was too far from the origin there were a number of overflow errors.
This clamps the camera to +/- 1B
Fixes #557

Fixed errors due to the camera being too far from the origin

---

amulet_map_editor/api/opengl/mesh/level/chunk/chunk_builder_cy.pyx

This is apparently required in some situations and is better to have it than not.
I hit the error of not having it once but I cannot reproduce it.

Added numpy.import_array()

---

amulet_map_editor/api/framework/amulet_ui.py
amulet_map_editor/api/framework/warning_dialog.py
amulet_map_editor/lang/en.lang

Adds a dialog to welcome new users and warn them about things such as backing up worlds and features that are not yet implemented.
This dialog opens before the actual Amulet UI does and has to be accepted to continue to the actual UI.

Added a dialog to welcome and warn new users

---

.github/stale.yml

This adds a config file that the stale bot needs to run.
It will only mark tickets as stale if they have the "state: more information needed" label.
7 days after having that tag with no activity the "state: stale" label will be added and the default message written.
14 days after that with no activity the issue will be closed.

Added a config for the stale bot

---

amulet_map_editor/api/wx/ui/traceback_dialog.py

Long error messages could flow off the end of the traceback dialog.
This goes back to the TextCtrl (not sure why I was using the ExpandoTextCtrl) which has scrolling enabled by default.

Made the traceback dialog scroll if the text is too long

---

amulet_map_editor/api/opengl/canvas/canvas.py
amulet_map_editor/api/opengl/canvas/event_canvas.py
amulet_map_editor/api/opengl/mesh/level/level.py
amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py
amulet_map_editor/programs/edit/api/canvas/edit_canvas.py
amulet_map_editor/programs/edit/api/renderer.py
amulet_map_editor/programs/edit/edit.py

Reading into OpenGL I found some issues with how we were doing things.
OpenGL functions cannot be called until the window is shown which might be the reason some users are getting errors.
Created a function that runs the first time the window is shown. Moved all the initial OpenGL state setting into this function. Enable is run once this function is done.
Other OpenGL initialisation is moved into the drawing functions which are run after the window is shown for the first time.

Improved the OpenGL handling

---

amulet_map_editor/programs/edit/api/canvas/edit_canvas.py

Moved the creation of the file panel to after the coordinates are set.
Previously it was constructed before the location was set but the event handlers were bound after the location was set.
This was an issue created by https://github.com/Amulet-Team/Amulet-Map-Editor/pull/678

Fixed the goto file panel button being all zeros

---

amulet_map_editor/programs/edit/api/operations/ui/fixed_pipeline.py

The save_picker & open_picker methods now have option capabilities for setting default paths if supplied, if none are supplied will set to a blank string which was the previous behavior.
- Code by gentlegiantJGC, implemented by StealthyX

Updated save_picker & open_picker with new options

---

amulet_map_editor/programs/edit/api/operations/ui/fixed_pipeline.py

The directory method now has an option for setting the default path if supplied, if none are supplied will be set to a blank string which was the previous behavior.
Code by gentlegiantJGC, implemented by StealthyX
- Sorry, missed this in the last pull request.

Updated _create_directory_picker with new option
